test: added unit tests
MapColonies/discrete-layer-storage pull request #14
Opened 2020-10-14 13:11 UTC by cl-shaharshavit-rnd

closes #13

2020-10-15 09:19 UTC, asafMasa requested changes
Good Job
🥇

2020-10-15 09:19 UTC, asafMasa commented on src/DAL/ConnectionManager.ts
> +      this.connection = await createConnection(connectionConfig);
add info log about connecting including connection params

2020-10-15 09:19 UTC, asafMasa commented on src/DAL/ConnectionManager.ts
> +import {
don't use PascalCase for file names

2020-10-15 09:19 UTC, asafMasa commented on src/controllers/ImagesController.ts
> +import { Request, Response } from 'express';
don't use PascalCase for file names

2020-10-15 09:19 UTC, asafMasa commented on src/services/ImageService.ts
> +import { injectable } from 'tsyringe';
don't use PascalCase for file names

2020-10-15 09:19 UTC, asafMasa commented on src/DAL/ImageDataRepository.ts
> +import { Repository, EntityRepository } from 'typeorm';
Don't use PascalCase for file names

2020-10-15 09:19 UTC, asafMasa commented on src/entity/ImageData.ts
> +import { Entity, Column, PrimaryColumn } from 'typeorm';
Don't use PascalCase for file names

2020-10-15 09:19 UTC, asafMasa commented on src/middleware/ErrorHandler.ts
>  import { MCLogger } from '@map-colonies/mc-logger';
Don't use PascalCase for file names

2020-10-15 10:14 UTC, asafMasa approved these changes

2020-10-18 05:10 UTC, cl-shaharshavit-rnd commented on src/DAL/ConnectionManager.ts
> +      this.connection = await createConnection(connectionConfig);
added

2020-10-18 06:50 UTC, merged